-- global settings
require('plugins')
require('editorSettings')
require('functions')
require('shortcuts')
require('theme')

-- plugins settings
require('plugins/airline')
require('plugins/ale')
require('plugins/emmet')
require('plugins/vim-go')
require('plugins/vimsence')
require('plugins/coc')
require('plugins/coc-explorer')
require('plugins/coc-git')
require('plugins/editorconfig')
require('plugins/undotree')
require('plugins/rainbow_parentheses')
require('plugins/context')
--require('plugins/deoplete')
