[directory]
truncation_length = 8
home_symbol = "~"

[username]
show_always = true
format = "[$user]($style)@"

[hostname]
ssh_only = false
format = "[$hostname]($style) "

#[git_metrics]
#disabled = false

#[character]
#success_symbol = "[➜](bold green) "
#error_symbol = "[➜ ](bold red) "
